import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.lely.com/techdocs/');
  await page.getByRole('heading', { name: 'Technical documents' }).click();
  await page.locator('#select2-id_q-container').click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('luna');
  await page.getByRole('treeitem', { name: 'Luna (all documents)' }).click();
  await page.getByLabel('Choose a language').locator('b').click();
  await page.getByRole('textbox').fill('tr');
  await page.getByRole('textbox').press('Enter');
  await page.getByLabel('E.g.').locator('b').click();
  await page.locator('#select2-id_type_number-container').click();
  await page.getByText('E.g.').click();
  await page.getByRole('textbox').fill('5.4');
  await page.getByRole('treeitem', { name: '5.4101.0050.1' }).click();
  await page.locator('li').filter({ hasText: /^Operator Manuals$/ }).click();
  await page.locator('#items-list').getByText('Turkish (tr)').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'View this document' }).click();
  const page1 = await page1Promise;
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#items-list').getByRole('img').click();
  const download = await downloadPromise;
  await page.getByRole('link', { name: ' Download' }).click();
  const download1Promise = page.waitForEvent('download');
  await page.goto('https://www.lely.com/techdocs/luna/');
  const download1 = await download1Promise;
  await page.locator('#items-list').getByText('Type number').click();
});